name: CentralBedfordshire
authority_code: centralbedfordshire
platform: acolnet
base_url: https://plantech.centralbedfordshire.gov.uk/PLANTECH/DCWebPages/acolnetcgi.gov
schedule: 0 3 * * *
requires_js: false
enabled: true
