name: HighPeak
authority_code: highpeak
platform: appsearchserv
base_url: http://planning.highpeak.gov.uk/portal/servlets/ApplicationSearchServlet
schedule: 0 3 * * *
requires_js: false
enabled: true
