name: Kirklees
authority_code: kirklees
platform: kirklees
base_url: https://www.kirklees.gov.uk/beta/planning-applications/search-for-planning-applications/default.aspx
schedule: 0 3 * * *
requires_js: false
enabled: true
